export const getContactAdminTemplate = ({
  name,
  email,
  message,
}: {
  name: string;
  email: string;
  message: string;
}) => {
  const accent = "#2eb09c";
  const primary = "#333d3f";

  return `
<div style="font-family: 'Segoe UI', Helvetica, Arial, sans-serif; background-color: #f1f5f9; padding: 40px 20px;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
    <div style="background-color: ${primary}; padding: 20px; text-align: center;">
      <h2 style="color: #ffffff; margin: 0; font-size: 18px; text-transform: uppercase; letter-spacing: 1px;">New Website Inquiry</h2>
    </div>
    <div style="padding: 30px;">
      <p style="color: #64748b; font-size: 14px; margin-bottom: 25px;">A new message has been submitted via the contact form. Please review the inquiry details below.</p>
      
      <table style="width: 100%; border-collapse: collapse;">
        <tr>
          <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #94a3b8; font-size: 13px; text-transform: uppercase; width: 140px;">Sender Name</td>
          <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: ${primary}; font-weight: bold;">${name}</td>
        </tr>
        <tr>
          <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #94a3b8; font-size: 13px; text-transform: uppercase;">Email Address</td>
          <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; font-weight: bold;">
            <a href="mailto:${email}" style="color: ${accent}; text-decoration: none;">${email}</a>
          </td>
        </tr>
        <tr>
          <td style="padding: 12px 0; color: #94a3b8; font-size: 13px; text-transform: uppercase; vertical-align: top;">Message</td>
          <td style="padding: 12px 0; color: ${primary}; line-height: 1.6; white-space: pre-line;">${message}</td>
        </tr>
      </table>

      <div style="margin-top: 35px; padding-top: 20px; border-top: 2px solid #f1f5f9; text-align: center;">
        <p style="font-size: 11px; color: #cbd5e1; text-transform: uppercase; letter-spacing: 1px;">Generated by IE Lung Web Portal</p>
      </div>
    </div>
  </div>
</div>`;
};
